(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var x2=function(a){a.T("cardstatechange",g.mL(a)&&g.nL(a)?1:0)},$sa=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.fk&&a.dataset){if(g.Sc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.nd("pollChoiceIndex"))},ata=function(a){return Math.pow(a,3)},bta=function(a){return 3*a*a-2*a*a*a},y2=function(a,b){var c=g.Do("use_default_events_client")?void 0:g.Kq;
(0,g.x)(b,function(d){d={csn:a,ve:g.Sr(d),eventType:4};var e={sl:g.Zr(a),kj:a};"UNDEFINED_CSN"==a?g.ls("visualElementShown",d,e):c?g.$p("visualElementShown",d,c,e):g.Lq("visualElementShown",d,e)})},z2=function(a,b){var c=g.Do("use_default_events_client")?void 0:g.Kq;
(0,g.x)(b,function(d){var e=void 0;e=void 0===e?!1:e;d={csn:a,ve:g.Sr(d),eventType:e?16:8};e={sl:g.Zr(a),kj:a,ME:e};"UNDEFINED_CSN"==a?g.ls("visualElementHidden",d,e):c?g.$p("visualElementHidden",d,c,e):g.Lq("visualElementHidden",d,e)})},C2=function(a){a=g.Pa(a);
delete A2[a];g.Nb(A2)&&B2&&B2.stop()},dta=function(){B2||(B2=new g.H(function(){cta()},20));
var a=B2;a.isActive()||a.start()},cta=function(){var a=(0,g.C)();
g.Ab(A2,function(b){eta(b,a)});
g.Nb(A2)||dta()},D2=function(a,b,c,d){g.Ln.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.A=a;this.H=b;this.duration=c;this.D=d;this.coords=[];this.progress=this.G=0;this.C=null},eta=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.G=1E3/(b-a.C);a.C=b;fta(a,a.progress);1==a.progress?(a.o=0,C2(a),a.md(),a.xm()):a.fb()&&a.Zt()},fta=function(a,b){g.Ma(a.D)&&(b=a.D(b));
a.coords=Array(a.A.length);for(var c=0;c<a.A.length;c++)a.coords[c]=(a.H[c]-a.A[c])*b+a.A[c]},gta=function(a,b){g.Oe.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.G;this.state=b.o},E2=function(a,b,c,d,e){D2.call(this,b,c,d,e);
this.element=a},F2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
E2.call(this,a,b,c,d,e)},G2=function(a){g.z.call(this);
this.u=a||window;this.o=[]},hta=function(a,b,c,d){c=(0,g.w)(c,d||a.u);
b=g.sp(b,"change",c,"iv-card-poll-choice-input");a.o.push(b)},H2=function(a){return a.baseUrl||null},I2=function(a,b){return(0,g.ze)((0,g.Hc)(a,b,void 0),function(c){return!!c})},ita=function(a,b,c){function d(ub){var nb=ub.hovercardButton;
if(!nb)return null;nb=nb.subscribeButtonRenderer;if(!nb)return null;var $d=f(nb.unsubscribedButtonText),sf=f(nb.subscribedButtonText);if(nb.subscribed){var Th=f(nb.subscriberCountWithUnsubscribeText);var Uh=f(nb.subscriberCountText)}else Th=f(nb.subscriberCountText),Uh=f(nb.subscriberCountWithSubscribeText);var fg=null;return ub.signinEndpoint&&(fg=g.Ib(ub,"signinEndpoint","webNavigationEndpointData","url"),!fg)?null:$d&&(sf||fg)?{subscribed:nb.subscribed,subscribeText:$d,subscribeCount:Th,unsubscribeText:sf,
unsubscribeCount:Uh,enabled:nb.enabled,signinUrl:fg,classic:ub.useClassicSubscribeButton}:null}
function e(ub){if(ub){var nb=[],$d=ub.videoId;$d&&nb.push("v="+$d);($d=ub.playlistId)&&nb.push("list="+$d);(ub=ub.startTimeSeconds)&&nb.push("t="+ub);return"/watch?"+nb.join("&")}}
function f(ub){if(!ub)return null;var nb=ub.simpleText;return nb?nb:ub.runs?(0,g.Hc)(ub.runs,function($d){return $d.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,q=null,t=null,u=null,y=null,B=!1,D=null,E=null,F=null,G=null,ha=null;if("VIDEO"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,t=f(b.videoDuration);else if("PLAYLIST"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,u=f(b.playlistLength);else if("CHANNEL"==k){if(B=g.Ib(l,"browseEndpoint","browseId"))y=B,m="/channel/"+y;n=!1;q="new";(B=!!b.isSubscribe)?D=d(b):E=f(b.subscribersText)}else"WEBSITE"==
k?((F=g.Ib(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==k&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(ha=f(b.additionalFeesText)),(n=g.Ib(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=g.Ib(b,"title","accessibility","accessibilityData","label");var na=b.endpoint?b.endpoint.clickTrackingParams:null,cc="";if(b.metadata){var vc=f(b.metadata);vc&&(cc=vc)}return{id:"element-"+c,type:k,title:f(b.title),metadata:cc,callToAction:f(b.callToAction),
Yw:b.image,iconUrl:F,left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:t,playlistLength:u,channelId:y,subscribeButton:D,subscribersText:E,isSubscribe:B,targetUrl:m,iG:n,Rb:{itct:na},FO:q,il:a?a:null,mG:b.isPlaceholder,impressionUrls:I2(b.impressionUrls||[],H2),aG:I2(b.hovercardShowUrls||[],H2),clickUrls:I2(l.loggingUrls||[],H2),visualElement:g.Qr(b.trackingParams),productPrice:G,
additionalFeesText:ha}},J2=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=I2(a.impressionUrls||[],H2);a.trackingParams&&(c.visualElement=g.Qr(a.trackingParams));c.elements=I2(a.elements||[],function(d,e){return ita(b,d,e)});
return c},K2=function(a){g.KL.call(this,a);
this.B=this.u=null;this.o={};this.G={};this.D=this.A=null;this.J=[];a=a.O();this.R=g.Oy(a)||g.Qy(a);this.N=!0;this.H=0;this.C=new g.Ar(this);g.A(this,this.C);this.C.M(this.player,g.jC("creatorendscreen"),this.XG);this.C.M(this.player,"crx_creatorendscreen",this.YG);this.C.M(this.player,"resize",this.hz);this.C.M(window,"focus",this.GN);this.load();var b=g.te("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Le(this,function(){g.ye(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},jta=function(a){return a.player.getVideoData().pc?"current":a.R?"new":"current"},L2=function(a){return"creator-endscreen-editor"===a.player.O().playerStyle},M2=function(a,b,c){c=void 0===c?!0:c;
g.CR(a.player.app,"creatorendscreen",void 0);a.A&&(a.A.dispose(),a.A=null,a.D.dispose(),a.D=null);for(var d in a.o)a.o[d].dispose();a.o={};a.G={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.H=0;if((a.u=b)&&b.elements){c&&kta(a);c=[];d=new g.gC(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.O().o||(a.A=new g.Q({F:"div",I:"ytp-ce-shadow"}),g.xL(a.player,a.A.element,4),a.D=new g.wN(a.A,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=lta(a,e);a.o[e.id]=f;a.G[e.id]=e;g.xL(a.player,f.element,4);var k=new g.gC(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);mta(a,f,e)}g.tL(a.player,c);
a.hz()}},kta=function(a){var b=g.Wr(),c=g.Yr();
c&&b&&a.u.visualElement&&g.rs(c,b,a.u.visualElement)},lta=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={F:"div",Z:["ytp-ce-element","ytp-ce-video"],P:{tabindex:"0","aria-label":b.il||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-covering-image",P:N2(b)},{F:"div",I:"ytp-ce-covering-shadow-top"},{F:"a",I:"ytp-ce-covering-overlay",P:{href:O2(a,b.targetUrl),tabindex:"-1"},L:[{F:"div",Z:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],P:{dir:g.Rn(b.title||"")},X:b.title},{F:"div",I:"ytp-ce-video-duration",X:b.videoDuration}]}]};
c=new g.Q(c);break;case "PLAYLIST":c={F:"div",Z:["ytp-ce-element","ytp-ce-playlist"],P:{tabindex:"0","aria-label":b.il||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-covering-image",P:N2(b)},{F:"div",I:"ytp-ce-covering-shadow-top"},{F:"a",I:"ytp-ce-covering-overlay",P:{href:O2(a,b.targetUrl),tabindex:"-1"},L:[{F:"div",Z:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],P:{dir:g.Rn(b.title||"")},X:b.title},{F:"div",I:"ytp-ce-playlist-count",L:[{F:"div",
I:"ytp-ce-playlist-icon"},{F:"div",I:"ytp-ce-playlist-count-text",X:b.playlistLength}]}]}]};c=new g.Q(c);break;case "CHANNEL":c={F:"div",Z:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],P:{tabindex:"0","aria-label":b.il||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-expanding-overlay",L:[{F:"div",I:"ytp-ce-expanding-overlay-hider"},{F:"div",I:"ytp-ce-expanding-overlay-background"},{F:"div",I:"ytp-ce-expanding-overlay-content",
L:[{F:"div",I:"ytp-ce-expanding-overlay-body",L:[{F:"div",I:"ytp-ce-expanding-overlay-body-padding",L:[{F:"a",Z:["ytp-ce-channel-title","ytp-ce-link"],P:{href:O2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Rn(b.title||"")},X:b.title},b.subscribeButton?{F:"div",I:"ytp-ce-subscribe-container",L:[{F:"div",I:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{F:"div",I:"ytp-ce-channel-subscribers-text",X:b.subscribersText}:"",b.metadata?{F:"div",Z:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
X:b.metadata}:""]}]}]}]},{F:"div",I:"ytp-ce-expanding-image",P:N2(b)}]};c=new g.Q(c);var d=g.fe(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.I(d,"ytp-ce-subscribe-button");if(a.player.O().o){var e=null;var f=b.Rb.itct}else e="endscreen",f=null;e=new g.cR(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":c={F:"div",Z:["ytp-ce-element","ytp-ce-website"],P:{tabindex:"0","aria-label":b.il||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-expanding-overlay",L:[{F:"div",I:"ytp-ce-expanding-overlay-hider"},{F:"div",I:"ytp-ce-expanding-overlay-background"},{F:"div",I:"ytp-ce-expanding-overlay-content",L:[{F:"div",I:"ytp-ce-expanding-overlay-body",
L:[{F:"div",I:"ytp-ce-expanding-overlay-body-padding",L:[{F:"div",I:"ytp-ce-website-title",P:{dir:g.Rn(b.title||"")},X:b.title},{F:"div",I:"ytp-ce-website-metadata",X:b.metadata},{F:"a",Z:["ytp-ce-website-goto","ytp-ce-link"],P:{href:O2(a,b.targetUrl),target:"_blank",tabindex:"-1"},X:b.callToAction}]}]}]}]},{F:"div",I:"ytp-ce-expanding-image",P:N2(b)},{F:"div",I:"ytp-ce-expanding-icon",P:nta(b.iconUrl)}]};c=new g.Q(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={F:"div",I:"ytp-ce-merchandise-price-container",
L:[{F:"div",I:"ytp-ce-merchandise-price",X:b.productPrice}]},b.additionalFeesText&&c.L.push({F:"div",I:"ytp-ce-merchandise-additional-fees",X:b.additionalFeesText})),c={F:"div",Z:["ytp-ce-element","ytp-ce-merchandise"],P:{tabindex:"0","aria-label":b.il||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-expanding-overlay",L:[{F:"div",I:"ytp-ce-expanding-overlay-hider"},{F:"div",I:"ytp-ce-expanding-overlay-background"},{F:"div",I:"ytp-ce-expanding-overlay-content",L:[{F:"div",
I:"ytp-ce-expanding-overlay-body",L:[{F:"div",I:"ytp-ce-expanding-overlay-body-padding",L:[{F:"div",I:"ytp-ce-merchandise-title",P:{dir:g.Rn(b.title||"")},X:b.title},c,{F:"div",I:"ytp-ce-merchandise-metadata",X:b.metadata},{F:"a",Z:["ytp-ce-merchandise-goto","ytp-ce-link"],P:{href:O2(a,b.targetUrl),target:"_blank",tabindex:"-1"},X:b.callToAction}]}]}]}]},{F:"div",I:"ytp-ce-expanding-image",P:N2(b)},{F:"div",I:"ytp-ce-merchandise-invideo-cta-container",L:[{F:"div",I:"ytp-ce-merchandise-invideo-cta",
X:b.callToAction}]}]},c=new g.Q(c)}b.mG&&g.I(c.element,"ytp-ce-placeholder");return c},N2=function(a){if(a.Yw)var b=a.Yw.thumbnails;
return nta(b?b[b.length-1].url:null)},nta=function(a){return a?{style:"background-image: url("+a+")"}:{}},mta=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.na("mouseenter",(0,g.w)(a.lt,a,b,c));b.na("mouseleave",(0,g.w)(a.eu,a,b,c));a.player.O().o||b.na("click",(0,g.w)(function(l){g.I(l.element,"ytp-ce-element-hover")},a,b));
b.na("click",(0,g.w)(a.EA,a,c));b.na("keypress",(0,g.w)(a.EA,a,c));b.na("focus",(0,g.w)(function(l,m){this.lt(l,m)},a,b,c));
b.na("blur",(0,g.w)(function(l,m){this.eu(l,m)},a,b,c));
b.na("touchstart",(0,g.w)(a.lt,a,b,c));var f=g.he("ytp-ce-expanding-overlay-hider",b.element);f&&b.M(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.Jn(b.element,"ytp-ce-element-hover");g.Jn(b.element,"ytp-ce-force-expand")});
b.na("keydown",(0,g.w)(function(l,m){this.N=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.w)(function(l,m,n){this.H+=n;0<this.H?(g.I(l.element,"ytp-ce-force-expand"),P2(this,m.id,!0)):(g.Jn(l.element,"ytp-ce-force-expand"),g.Jn(l.element,"ytp-ce-element-hover"),P2(this,m.id,!1))},a,b,c);
c=(0,g.w)(function(l,m){m&&(l.na("blur",g.Qa(function(){"none"!=m.style.display&&a.N&&m.focus()})),l.M(m,"focus",d),l.M(m,"blur",e))},a,b);
c(g.he("ytp-sb-subscribe",b.element));c(g.he("ytp-sb-unsubscribe",b.element));b.na("focus",d);b.na("blur",e)},O2=function(a,b){var c=a.player.O();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.rz(c)+b}else return"";return b},P2=function(a,b,c){a.A&&(c?a.D.show():a.D.hide());
for(var d in a.o)d!=b&&g.J(a.o[d].element,"ytp-ce-element-shadow-show",c)},Q2=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||0==b.length||L2(a))c&&c();else{b=ota(a,b);var e=0,f=!1,k=new g.H(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Xq(b[a],d)}},R2=function(a,b,c){Q2(a,b.clickUrls,c);
(a=g.Yr())&&b.iG&&g.ts(a,b.visualElement)},ota=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(pta(b[e],c));return d},pta=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},qta=function(a){return Array.isArray(a)&&a.length?a[0]:a},S2=function(a){return"string"===typeof a?a:""},T2=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},sta=function(a){var b=rta;
if(null==a)return null;if(g.La(a)){var c=[];(0,g.x)(a,function(d){(d=b(d))&&c.push(d)});
return c}return(a=b(a))?[a]:[]},tta=function(a){this.externalId=a},uta=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},U2=function(a){if(!a)return null;
var b=g.Bc(S2(a.value));b=g.zc(b);if(!b)return null;var c=T2(a.target,vta,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new uta(b,c,"true"==d||"false"==d?"true"==d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},V2=function(a){return a.value?a.value:null},wta=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},rta=function(a){if(!a)return null;
var b=T2(a.type,xta),c=T2(a.trigger,yta),d=qta(a.url);d=U2(d?d:null);a=qta(a.subscribeData);var e=a?a:null;e?(a=S2(e.external_user_id),e=S2(e.subscription_token),a=a&&e?new tta(a):null):a=null;return b?new wta(b,c,d,a):null},W2=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.o=d||[];this.data=e},zta=function(a,b){return g.Ya(a.o,b,void 0)},Ata=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},Bta=function(a,b){this.merchant=a;
this.price=b},Cta=function(a){this.o=a},Dta=function(a,b,c){b&&(c?X2(a,(0,g.Hc)(b,g.Qa(function(d,e){return g.kn(e,d)},c))):X2(a,b))},X2=function(a,b,c,d){var e=1,f=-1;
if(c){var k=!1;var l=function(){e--;e||k||(clearTimeout(f),k=!0,c())};
f=setTimeout(function(){k=!0;c()},1E3)}(0,g.x)(b||[],function(m){e++;
g.Xq(m,l)});
d&&(e++,0!=d&&a.o.sendVideoStatsEngageEvent(d,l))},Eta=function(a,b,c,d,e,f,k){this.o=a;
this.A=b;this.B=c;this.videoData=d;this.logger=e;this.K=f;this.u=k},Y2=function(a,b){this.o=a;
this.A=b},Hta=function(a,b){var c=[];
(0,g.x)(b.choices,function(k){c.push(Fta(b,k))},a);
var d={F:"ul",P:{role:"radiogroup"},L:c},e={};b.nj&&(e["aria-label"]=g.vM("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{F:"div",I:"iv-card-content",L:[Z2("h2",e,b.title),{F:"form",L:[{F:"fieldset",L:[d]}]}]}];b.nj&&(f.push("iv-card-unavailable"),d.push({F:"div",Z:["iv-card-sign-in"],L:[{F:"h2",X:"Want to vote?"},{F:"a",Z:["iv-card-sign-in-button","iv-button"],P:{href:V2(b.nj)},L:[{F:"span",Z:["iv-button-content"],X:"Sign in"}]}]}));f=new g.Q({F:"div",
Z:f,L:d});d=f.element;Gta(b,d);hta(a.o.o,d,g.Qa(a.B,b),a);(0,g.x)(g.ge("iv-card-poll-choice-input",d),function(k){this.o.o.na(k,"focus",g.Qa(this.u,!0));this.o.o.na(k,"blur",g.Qa(this.u,!1))},a);
b.nj&&(d=g.he("iv-card-sign-in-button",d),a.A(d,b.nj,b.id,b.Rb,b.Ic.click,5));return f},Ita=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.WO?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.lG&&b.tw?{F:"span",Z:d,P:e,X:b.tw}:"";c={F:"div",Z:["iv-card",c],L:[{F:"a",I:"iv-click-target",P:{href:V2(b.url)},L:[$2(b.rj,d?{F:"div",I:"iv-card-image-text",L:[d,b.priceText]}:""),{F:"div",I:"iv-card-content",L:[{F:"h2",I:"iv-card-primary-link",X:b.title},a3(a,b)]}]}]};c=new g.Q(c);b3(a,g.ge("iv-click-target",c.element),b,b.url);return c},c3=function(a){return a.customMessage?
Z2("div","iv-card-message",a.customMessage):""},$2=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{F:"div",I:"iv-card-image",P:{style:c},L:d}},a3=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.x)(b.metaInfo,function(d){c.push(Z2("li","",d))},a);
return{F:"ul",I:"iv-card-meta-info",L:c}},Fta=function(a,b){return{F:"li",
I:Ata(a,b.index),L:[{F:"label",L:[{F:"input",I:"iv-card-poll-choice-input",P:{type:"checkbox",role:"radio",name:a.id.replace(/[^a-z0-9-]/gi,"-")+b.index.toString(),value:b.index.toString(),"data-poll-choice-index":b.index.toString()}},{F:"span",I:"iv-card-poll-choice-text",L:[{F:"span",I:"iv-card-poll-choice-percent"},Z2("span",void 0,b.desc)]}]},{F:"div",I:"iv-card-poll-result",L:[{F:"div",I:"iv-card-poll-result-bar"}]}]}},Z2=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&
(b={"class":b.join(" ")}):b={};
b.dir=g.Rn(c);return{F:a,P:b,X:c}},Jta=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.zn&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.zn+");");c.dir=g.Rn(a.customMessage);var d=[{F:"span",X:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({F:"span",I:"iv-card-link-icon"}));return{F:"div",Z:b,P:c,L:d}},Gta=function(a,b){var c=0;
(0,g.x)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.he(Ata(a,e.index),b);e=e.count/c;null==a.Ce&&(e=0);g.J(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.Ce==d);f.getElementsByTagName("input")[0].checked=a.Ce==d;var k=Math.floor(100*e).toFixed(0),l=g.he("iv-card-poll-choice-percent",f);g.De(l,g.vM("$PERCENT%",{PERCENT:k}));f=g.he("iv-card-poll-result-bar",f);g.yh(f,"transform","scaleX("+e.toFixed(2)+")")}g.J(b,"iv-card-poll-voted",null!=a.Ce);g.J(b,"iv-card-poll-expanded",
null!=a.Ce&&1<a.choices.length)},b3=function(a,b,c,d){d&&(0,g.x)(b,function(e){this.A(e,d,c.id,c.Rb,c.Ic.click,5)},a)},Kta=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},Lta=function(a,b){return b?b:Kta(a)?"current":"new"},d3=function(a,b){g.z.call(this);
var c=this;this.Ha=a;this.context=b;this.qv=!1;this.fa=new Map;this.ka=new Map;this.context.K.addEventListener(g.jC("annotations_module"),function(d){(d=c.fa.get(d))&&d.apply(c)});
this.context.K.addEventListener("crx_annotations_module",function(d){(d=c.ka.get(d))&&d.apply(c)})},Mta=function(a,b,c,d,e){var f=V2(b);
if(f){var k=Lta(f,b.target),l=(0,g.w)(function(){b.o&&this.context.K.pauseVideo();var m=this.context.videoData.pc||!1,n=g.gq(f||"");m&&n&&(n.v||n.list)?g.xT(this.context.K.app,n.v,c,n.list,!1,void 0):g.NN(f||"","current"==k?"_top":void 0,c)},a);
"new"==k&&(l(),l=null);X2(a.context.logger,d,l,e);Kta(f)||(a=g.Yr(),d=c.itct,a&&d&&g.ts(a,g.Qr(d)))}},Nta=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},e3=function(a,b,c){return{ky:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
uC:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
oq:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl})}},h3=function(a,b,c){d3.call(this,b,c);
var d=this;this.u=a;this.ca=this.Fa=this.C=this.Da=!1;this.ga=null;this.ba=new g.H(g.Ia,c.B.gb?4E3:3E3);g.A(this,this.ba);this.wa=new g.H(g.Ia);g.A(this,this.wa);this.H=new Y2(c,(0,g.w)(this.Mk,this),(0,g.w)(this.Lo,this));this.V=new g.Q({F:"div",I:"iv-drawer",P:{id:"iv-drawer"},L:[{F:"div",I:"iv-drawer-header",P:{"aria-role":"heading"},L:[{F:"span",I:"iv-drawer-header-text"},{F:"button",Z:["iv-drawer-close-button","ytp-button"],P:{"aria-label":"Hide cards",tabindex:"0"}}]},{F:"div",I:"iv-drawer-content"}]});
g.A(this,this.V);this.D=this.V.element;this.ra=new g.wN(this.V,330);g.A(this,this.ra);this.Aa=g.he("iv-drawer-header-text",this.D);this.B=g.he("iv-drawer-content",this.D);this.A=[];this.ya=this.S=this.G=this.ea=this.o=null;this.W=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.Fa&&f3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Fa=d.C)&&g3(d)});
this.N=this.J=this.aa=null;this.R=0},Ota=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){f3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){g3(a)});
var c=b.data.headerText;g.De(a.Aa,c);a.S&&a.S.setAttribute("title",c);a.aa=g.Qr(b.data.trackingParams);a.N=g.Qr(b.data.closeTrackingParams);a.J=g.Qr(b.data.iconTrackingParams)},Pta=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.R;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.R,type:"simple",teaserText:g.S(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Rb:i3(a,c,b,d),sponsored:!1,Ic:e3(d,e,d.command),ce:d.trackingParams?g.Qr(d.trackingParams):null,Wd:e.trackingParams?
g.Qr(e.trackingParams):null,Ad:f&&f.trackingParams?g.Qr(f.trackingParams):null,imageUrl:j3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.S(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,zn:null,title:d.title?g.S(d.title):"",customMessage:d.callToAction?g.S(d.callToAction):"",url:d.command.urlEndpoint.url?U2({pause_on_navigation:!a.context.videoData.za,target:"new",value:d.command.urlEndpoint.url}):null};k3(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.R,type:"collaborator",teaserText:g.S(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Rb:i3(a,c,b,d),sponsored:!1,Ic:e3(d,e,d.endpoint),ce:d.trackingParams?g.Qr(d.trackingParams):null,Wd:e.trackingParams?g.Qr(e.trackingParams):null,Ad:f&&f.trackingParams?
g.Qr(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.S(d.customText):null,CB:j3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.S(d.channelName):"",metaInfo:[d.subscriberCountText?g.S(d.subscriberCountText):""],url:U2({pause_on_navigation:!a.context.videoData.za,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};k3(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.R,type:"playlist",teaserText:g.S(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Rb:i3(a,c,b,d),sponsored:!1,Ic:e3(d,e,d.action),ce:d.trackingParams?g.Qr(d.trackingParams):null,Wd:e.trackingParams?g.Qr(e.trackingParams):null,Ad:f&&f.trackingParams?g.Qr(f.trackingParams):
null,rj:j3(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.S(d.customMessage):null,playlistVideoCount:g.S(d.playlistVideoCount),title:d.playlistTitle?g.S(d.playlistTitle):"",metaInfo:[d.channelName?g.S(d.channelName):"",d.videoCountText?g.S(d.videoCountText):""],url:U2({pause_on_navigation:!a.context.videoData.za,target:"new",value:Nta(d.action)})};k3(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.R,type:"video",teaserText:g.S(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Rb:i3(a,c,b,d),sponsored:!1,Ic:e3(d,e,d.action),ce:d.trackingParams?g.Qr(d.trackingParams):null,Wd:e.trackingParams?g.Qr(e.trackingParams):null,Ad:f&&f.trackingParams?g.Qr(f.trackingParams):null,rj:j3(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.S(d.lengthString):null,customMessage:d.customMessage?g.S(d.customMessage):null,title:d.videoTitle?g.S(d.videoTitle):"",metaInfo:[d.channelName?g.S(d.channelName):"",d.viewCountText?g.S(d.viewCountText):""],isLiveNow:!!d.badge,url:U2({pause_on_navigation:!a.context.videoData.za,target:"new",value:Nta(d.action)})};k3(a,c)}a.R++},j3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height==b||290==a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},i3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId,itct:d.trackingParams}},Rta=function(a,b){var c=Qta(a,b);
c&&(c==a.o&&(a.o=null),a.u.removeCueRange(c.card.id),g.ye(c.mr),g.eb(a.A,c),a.Cn(),l3(a))},f3=function(a,b,c){if(!a.C){a.ra.show();
a.ea=new g.H(function(){g.I(a.context.K.getRootNode(),g.AM.IV_DRAWER_OPEN)},0);
a.ea.start();a.ga=g.jp(a.B,"mousewheel",(0,g.w)(a.RL,a));a.C=!0;var d=g.Yr();d&&a.aa&&a.N&&y2(d,[a.aa,a.N]);var e={TRIGGER_TYPE:b};(0,g.x)(a.A,function(f){f.Ly||(f.Ly=!0,Dta(a.context.logger,f.card.Ic.ky,e));d&&y2(d,[f.card.ce])});
x2(a.u);c&&(a.G=new g.H(function(){a.va=a.S;a.ya.focus()},330),a.G.start())}},g3=function(a){a.C&&(a.ra.hide(),g.kp(a.ga),a.ga=null,g.Jn(a.context.K.getRootNode(),g.AM.IV_DRAWER_OPEN),a.C=!1,x2(a.u),a.G&&a.G.stop(),a.G=new g.H(function(){a.va&&(a.va.focus(),a.va=null)},330),a.G.start())},Sta=function(a){var b=g.he("iv-drawer-close-button",a.D);
a.context.o.na(b,"click",a.uE,a);a.context.o.na(a.B,"touchend",function(){a.ba.start()});
a.context.o.na(a.B,"scroll",a.HE,a);a.context.u.subscribe("onHideControls",function(){a.ca=!0});
a.context.u.subscribe("onShowControls",function(){a.ca=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.ca=g.Hn(a.u.getRootNode(),"ytp-autohide")});
a.W.push(g.Uo("iv-button-shown",a.sG,a));a.W.push(g.Uo("iv-button-hidden",a.rG,a));a.W.push(g.Uo("iv-teaser-shown",a.vG,a));a.W.push(g.Uo("iv-teaser-hidden",a.uG,a));a.W.push(g.Uo("iv-teaser-clicked",a.tG,a))},k3=function(a,b){a.Da||(g.In(a.xa(),[g.AM.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]),g.xL(a.u,a.D,5),Sta(a),a.S=g.he("ytp-cards-button",a.u.getRootNode()),a.ya=g.he("iv-drawer-close-button",a.D),a.Da=!0);Rta(a,b.id);var c=Tta(a,b);if(c){var d={card:b,mr:c.element,Ly:!1},e=Uta(a,d);g.lb(a.A,e,0,d);c.da(a.B,e);a.Cn();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Qa(a.pO,d)):(c=1E3*a.context.K.getCurrentTime(),5E3>c&&c>b.startMs&&a.hC(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Qa(a.hC,d)),l3(a))}},Tta=function(a,b){switch(b.type){case "simple":var c=
a.H;
var d=b.displayDomain?{F:"div",I:"iv-card-image-text",X:b.displayDomain}:"";var e=Jta(b);d={F:"div",Z:["iv-card"],L:[{F:"a",I:"iv-click-target",P:{href:V2(b.url)},L:[$2(b.imageUrl,d),{F:"div",I:"iv-card-content",L:[Z2("h2",void 0,b.title),e]}]}]};d=new g.Q(d);b3(c,g.ge("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.H,d={F:"div",Z:["iv-card","iv-card-channel"],L:[{F:"a",Z:["iv-click-target"],P:{href:V2(b.url),"data-ytid":b.channelId},L:[$2(b.CB),{F:"div",I:"iv-card-content",
L:[c3(b),{F:"h2",I:"iv-card-primary-link",X:b.title},a3(c,b)]}]}]},d=new g.Q(d),b3(c,g.ge("iv-click-target",d.element),b,b.url),d;case "episode":return Ita(a.H,b,"iv-card-episode");case "movie":return Ita(a.H,b,"iv-card-movie");case "playlist":return c=a.H,d={F:"div",Z:["iv-card","iv-card-playlist"],L:[{F:"a",I:"iv-click-target",P:{href:V2(b.url)},L:[$2(b.rj,{F:"div",I:"iv-card-image-overlay",L:[{F:"span",I:"iv-card-playlist-video-count",X:b.playlistVideoCount}]}),{F:"div",I:"iv-card-content",L:[c3(b),
Z2("h2","iv-card-primary-link",b.title),a3(c,b)]}]}]},d=new g.Q(d),b3(c,g.ge("iv-click-target",d.element),b,b.url),d;case "poll":return Hta(a.H,b);case "productListing":c=a.H;var f=!g.bb(b.offers);d=["iv-card"];e="";var k=Jta(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",f=b.offers[0],k=[],f.price&&k.push({F:"div",I:"iv-card-offer-price",X:f.price}),f.merchant&&k.push({F:"div",I:"iv-card-offer-merchant",X:f.merchant}),k={F:"div",L:k});d={F:"div",Z:d,P:{tabindex:"0"},L:[{F:"a",
Z:["iv-card-image","iv-click-target"],P:{style:"background-image: url("+b.imageUrl+");",href:V2(b.url),"aria-hidden":"true",tabindex:"-1"}},{F:"div",I:"iv-card-content",L:[b.sponsored?{F:"div",I:"iv-card-sponsored",L:["Sponsored",{F:"div",I:"iv-ad-info-container",L:[{F:"div",I:"iv-ad-info",X:"{{adInfo}}"},{F:"div",I:"iv-ad-info-icon-container",L:[{F:"div",I:"iv-ad-info-icon"},{F:"div",I:"iv-ad-info-callout"}]}]}]}:"",{F:"a",I:"iv-click-target",P:{href:V2(b.url)},L:[Z2("h2",e,b.title),k]}]}]};d=new g.Q(d);
e=g.te("span");g.De(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.sb(e,"adInfo");b3(c,g.ge("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.H,d=b.isLiveNow?{F:"span",Z:["yt-badge","yt-badge-live"],X:"LIVE NOW"}:"",d={F:"div",Z:["iv-card","iv-card-video"],L:[{F:"a",I:"iv-click-target",P:{href:V2(b.url)},L:[$2(b.rj,b.videoDuration?{F:"span",I:"iv-card-video-duration",X:b.videoDuration}:""),{F:"div",I:"iv-card-content",
L:[c3(b),Z2("h2","iv-card-primary-link",b.title),a3(c,b),d]}]}]},d=new g.Q(d),b3(c,g.ge("iv-click-target",d.element),b,b.url),d}return null},Uta=function(a,b){if(0==a.A.length)return 0;
var c=g.Za(a.A,function(d){return b.card.startMs>d.card.startMs||b.card.startMs==d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1==c?0:c+1},Vta=function(a){return a.o?"productListing"==a.o.card.type:(0,g.zi)(a.A,function(b){return"productListing"==b.card.type})},l3=function(a){g.J(a.u.getRootNode(),"ytp-cards-shopping-active",Vta(a))},Wta=function(a,b){if(a.V.Ka()){var c=new D2([0,
a.B.scrollTop],[0,b.mr.offsetTop],600,bta);a.context.A.na(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.A.na(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.Lu(a.V,!0),a.B.scrollTop=b.mr.offsetTop,g.Lu(a.V,!1)},m3=function(a){return a.o&&a.o.card?a.o.card:a.A[0]&&a.A[0].card?a.A[0].card:null},Qta=function(a,b){return g.Ya(a.A,function(c){return c.card.id==b})},n3=function(a,b,c){d3.call(this,a,b);
this.annotation=c;this.isActive=!1},Xta=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},o3=function(a,b,c){n3.call(this,a,b,c);
this.u=null;this.G=!1;this.A=null;this.B=!1;this.o=this.D=this.C=null},p3=function(a,b,c){n3.call(this,a,b,c);
this.J=this.C=this.R=!1;this.G=5E3;this.B=null;this.H=g.se("DIV","iv-promo-contents");this.u=this.A=this.o=null;this.D=new g.H(function(){this.o.setAttribute("aria-hidden",!0);g.Sh(this.A,!1);g.Sh(this.u,!0)},700,this);
g.A(this,this.D)},Yta=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.G=b.collapse_delay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.xa().setAttribute("aria-hidden",!0);a.xa().setAttribute("aria-label","Promotion");a.xa().tabIndex=0;var e=a.annotation.lc(),f=b.image_url;if(f){var k=g.se("DIV",["iv-promo-img","iv-click-target"]);f=g.se("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.se("SPAN","iv-promo-video-duration",
b.video_duration),k.appendChild(f)):b.playlist_length&&(f=g.se("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.Mk(k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=g.se("A","iv-promo-txt"),g.bd(f,V2(e)),a.o=f):a.o=g.se("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.se("P",null,g.se("STRONG",null,b.text_line_1));var m=g.se("P",null,g.se("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");
g.O(a.context.B.experiments,"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.se("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.se("BUTTON",["iv-button","iv-promo-button"],g.se("SPAN","iv-button-content",f));var q=g.se("DIV","iv-promo-button-container");q.appendChild(f);e&&a.Mk(a.xa(),e,a.annotation.id,b.session_data,void 0,c)}g.I(a.o,"iv-click-target");e&&a.Mk(a.o,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=g.se("P",
null,g.se("SPAN",null,b.text_line_1)),m=g.se("P",null,g.se("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.se("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.I(a.o,"iv-click-target"),e&&a.Mk(a.o,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.o.appendChild(l);m&&a.o.appendChild(m);a.H.appendChild(a.o);q&&a.H.appendChild(q);c=g.se("DIV","iv-promo-actions");a.u=g.se("BUTTON",["iv-promo-expand","ytp-button"]);a.u.title="Expand";a.context.o.na(a.u,"click",g.Qa(a.ys,
5E3),a);c.appendChild(a.u);g.Sh(a.u,!1);a.context.o.na(a.xa(),"mouseover",a.DF,a);a.context.o.na(a.xa(),"mouseout",a.CF,a);a.context.o.na(a.xa(),"touchend",g.Qa(a.ys,5E3),a);a.A=g.se("BUTTON",["iv-promo-close","ytp-button"]);a.A.title="Close";a.context.o.na(a.A,"click","cta"==a.annotation.style&&b.text_line_3?a.vF:a.uF,a);c.appendChild(a.A);g.In(a.xa(),d);k&&(a.xa().appendChild(k),n&&k.appendChild(n));a.xa().appendChild(a.H);a.xa().appendChild(c)},Zta=function(a){a.C||a.J||a.B||(g.I(a.xa(),"iv-promo-collapsed"),
a.C=!0,a.D.start())},$ta=function(a){a.D.stop();
a.C&&(g.Kn(a.xa(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.C=!1,a.o&&a.o.removeAttribute("aria-hidden"),g.Sh(a.u,!1),g.Sh(a.A,!0))},aua=function(a,b){a.B||(a.B=g.Zf(function(){q3(this);
Zta(this)},b,a))},q3=function(a){a.B&&(g.v.clearTimeout(a.B),a.B=null)},r3=function(a){g.KL.call(this,a);
this.R=!1;this.J=0;this.G={};this.W=new Cta(a);this.C=new g.Ar(this);g.A(this,this.C);this.D=this.A=null;this.C.M(this.player,"onVideoAreaChange",(0,g.w)(this.T,this,"onVideoAreaChange"));this.C.M(this.player,"onHideControls",(0,g.w)(this.T,this,"onHideControls"));this.C.M(this.player,"onShowControls",(0,g.w)(this.T,this,"onShowControls"));this.C.M(this.player,"resize",(0,g.w)(this.T,this,"resize"));this.C.M(this.player,"presentingplayerstatechange",(0,g.w)(this.T,this,"presentingplayerstatechange"));
this.subscribe("presentingplayerstatechange",this.mM,this);this.subscribe("resize",this.Hp,this);this.player.O().J.subscribe("vast_info_card_add",this.oB,this);this.V=new g.Ar(this);g.A(this,this.V);this.S=g.se("DIV","video-custom-annotations");this.u=new g.Q({F:"div",Z:["ytp-player-content","ytp-iv-player-content"]});g.A(this,this.u);g.xL(this.player,this.u.element,4);this.u.hide();this.B=new g.Q({F:"div",Z:["ytp-iv-video-content"]});g.A(this,this.B);g.ve(this.B.element,g.se("DIV","video-annotations",
this.S));this.H=this.o=null;this.N=[];bua(this)&&this.load();var b=g.te("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Le(this,function(){g.ye(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},cua=function(){var a=g.se("DIV",["annotation",
"annotation-type-custom"]);g.Sh(a,!1);return a},dua=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},bua=function(a){var b=a.player.O();
a=a.player.getVideoData();return 1==(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.ZC||b.J.get(a.videoId)||g.IB(a)||g.JB(a)?!0:!1},eua=function(a,b){var c=!b.isCued()&&!g.U(b,1024);
g.Lu(a.u,c);g.Lu(a.B,c)},fua=function(a,b,c){a.R=!0;
a.D=g.yq(b,c)},gua=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Na(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(gua(a,e))}return c},hua=function(a,b,c){return!(a.loaded&&a.J==b&&a.player.getVideoData().videoId==
c)},kua=function(a){var b=a.player.getVideoData();
if(b.ae){var c=a.player.O().J.get(b.videoId);if(c){var d={format:"XML",Xd:{},method:"POST",withCredentials:!0};d.md=(0,g.w)(function(e,f,k){hua(this,e,f)||(e=g.sq(k)&&k.responseXML?k.responseXML:null)&&s3(this,e)},a,a.J,b.videoId);
g.Ap()&&(d.md=iua(a,d.md));d.ub={ic_only:"1"};jua(d,c);a.R=!0;g.yq(b.ae,d)}}},jua=function(a,b){a.method="POST";
a.ub=a.ub||{};b.Gn&&(a.ub.ic_coll=b.Gn);b.Hn&&(a.ub.ic_xml=b.Hn);b.Vm&&(a.ub.ic_track=b.Vm)},lua=function(a){var b=new g.Q({F:"div"});
g.Sh(b.element,!1);var c=new h3(a.player,b.element,t3(a));g.A(c,b);b.da(a.u.element);c.Km();return c},t3=function(a){if(!a.H){var b=new G2(a);
g.A(a,b);var c=new g.x1(a);g.A(a,c);a.H=new Eta(b,c,a.player.O(),a.player.getVideoData(),a.W,a.player,a.Th)}return a.H},s3=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Yr();if(e){var f=g.Wr();f&&g.ms(g.Do("use_default_events_client")?void 0:g.Kq,e,f,[g.Qr(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var k=gua(a,d[e]);f=null;try{if(k){var l=k.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var q=T2(k.type,mua),t=T2(k.style,nua),u=S2(k.data),y=0!=u.length?JSON.parse(u):{},B=sta(k.action);f=n&&q?new W2(n,q,t,B,y):null}else f=null}catch(ha){}if(f){a:{switch(f.type){case "branding":case "promotion":k=
!0;break a}k=!1}if(k){k=a;m=f;var D=cua(),E=null;switch(m.type){case "branding":if(k.player.O().Aa)break;k.u.element.appendChild(D);E=new o3(D,t3(k),m);break;case "promotion":g.xL(k.player,D,4),E=new p3(D,t3(k),m)}E&&E.Km();if(k=E)g.A(a,k),a.G[f.id]=k}else if("card"==f.type||"drawer"==f.type){a.o||(a.o=lua(a),g.A(a,a.o));if("card"==f.type){if(c=a.o,E=f&&f.data&&f.data.card_type)switch(k=f.data.tracking||{},k={ky:k.impression,click:k.click,close:k.close,uC:k.teaser_impression,oq:k.teaser_click},m=
f.data.tracking_params||{},D=null,E){case "collaborator":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Rb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Ic:k,ce:m.card?g.Qr(m.card):null,Wd:m.teaser?g.Qr(m.teaser):null,Ad:m.icon?g.Qr(m.icon):null,channelId:f.data.channel_id,customMessage:f.data.custom_message?f.data.custom_message:null,CB:f.data.image_url,
title:f.data.title,metaInfo:f.data.meta_info,url:U2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};k3(c,f);break;case "episode":case "movie":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Rb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Ic:k,ce:m.card?g.Qr(m.card):null,Wd:m.teaser?g.Qr(m.teaser):null,
Ad:m.icon?g.Qr(m.icon):null,rj:f.data.image_url,tw:f.data.badge_symbol||"",priceText:f.data.price_text||"",title:f.data.title,metaInfo:f.data.meta_info,lG:!!f.data.is_paygated,WO:!!f.data.user_has_entitlement,url:U2({target:f.data.target||"new",value:f.data.url})};k3(c,f);break;case "playlist":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Rb:f.data.session_data||
{},sponsored:f.data.sponsored||!1,Ic:k,ce:m.card?g.Qr(m.card):null,Wd:m.teaser?g.Qr(m.teaser):null,Ad:m.icon?g.Qr(m.icon):null,rj:f.data.image_url,playlistVideoCount:f.data.playlist_video_count,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,url:U2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};k3(c,f);break;case "poll":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,
teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Rb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Ic:k,ce:m.card?g.Qr(m.card):null,Wd:m.teaser?g.Qr(m.teaser):null,Ad:m.icon?g.Qr(m.icon):null,title:f.data.title,choices:f.data.choices,Ce:f.data.hasOwnProperty("old_vote")?f.data.old_vote:null,nj:f.data.signin_url?U2({target:"current",value:f.data.signin_url}):null,hP:f.data.hasOwnProperty("xsrf_token")?f.data.xsrf_token:null};k3(c,f);break;case "productListing":f.data.signin_url&&
(D=U2({target:"current",value:f.data.signin_url}));E=[];for(var F=f.data.offers||[],G=0;G<F.length;G++)E.push(new Bta(g.jd(F[G].merchant),g.jd(F[G].price)));f={wT:!1,id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Rb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Ic:k,ce:m.card?g.Qr(m.card):null,Wd:m.teaser?g.Qr(m.teaser):null,Ad:m.icon?g.Qr(m.icon):null,
imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,zn:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:U2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url}),nj:D,TT:f.data.signin_title?f.data.signin_title:null,ST:f.data.signin_message?f.data.signin_message:null,offers:E};k3(c,f);break;case "simple":f=
{id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Rb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Ic:k,ce:m.card?g.Qr(m.card):null,Wd:m.teaser?g.Qr(m.teaser):null,Ad:m.icon?g.Qr(m.icon):null,imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,zn:f.data.button_icon_url?f.data.button_icon_url:
null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:U2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};k3(c,f);break;case "video":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Rb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Ic:k,ce:m.card?g.Qr(m.card):null,Wd:m.teaser?
g.Qr(m.teaser):null,Ad:m.icon?g.Qr(m.icon):null,rj:f.data.image_url,videoDuration:f.data.video_duration||null,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,isLiveNow:!!f.data.is_live_now,url:U2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})},k3(c,f)}}else Ota(a.o,f);c=!0}}}c&&(x2(a.player),a.Hp())},oua=function(a,b){var c=!1;
a.o||(a.o=lua(a),g.A(a,a.o));for(var d=g.p(b.cards||[]),e=d.next();!e.done;e=d.next())Pta(a.o,e.value.cardRenderer),c=!0;c&&(c=a.o,d=b.headerText?g.S(b.headerText):"",g.De(c.Aa,d),c.S&&c.S.setAttribute("title",d),c.aa=b.trackingParams?g.Qr(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.Qr(b.closeButton.infoCardIconRenderer.trackingParams):null,c.J=b.icon.infoCardIconRenderer.trackingParams?g.Qr(b.icon.infoCardIconRenderer.trackingParams):null,x2(a.player),a.Hp())},
pua=function(a,b,c,d,e){if(!a.player.O().Aa){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new wta("openUrl","click",new uta("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var k=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:k.height,image_type:1,image_url:k.url,image_width:k.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;k=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.S(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(k=g.S(b.subscriberCountText))):(b.subscriberCountText&&(e=g.S(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(k=g.S(b.subscriberCountWithSubscribeText)));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.S(b.unsubscribedButtonText),subscribeCount:e,unsubscribeText:g.S(b.subscribedButtonText),unsubscribeCount:k,enabled:b.enabled,classic:!1,subscribed:b.subscribed,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new W2(c,"branding","branding",f,d);d=cua();a.u.element.appendChild(d);f=new o3(d,t3(a),f);f.Km();g.A(f,f);a.G[c]=f}},iua=function(a,b){return(0,g.w)(function(){if(!this.ha()){var c=
Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Qa.apply(window,c);this.N.push(g.yp(b))}},a)},A2={},B2=null;g.Sa(D2,g.Ln);g.h=D2.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.A;else if(this.fb())return!1;C2(this);this.startTime=a=(0,g.C)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.Ep();this.se("play");-1==this.o&&this.se("resume");this.o=1;var b=g.Pa(this);b in A2||(A2[b]=this);dta();eta(this,a);return!0};
g.h.stop=function(a){C2(this);this.o=0;a&&(this.progress=1);fta(this,this.progress);this.se("stop");this.xm()};
g.h.pause=function(){this.fb()&&(C2(this),this.o=-1,this.se("pause"))};
g.h.Y=function(){0==this.o||this.stop(!1);this.se("destroy");D2.Lb.Y.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Zt=function(){this.se("animate")};
g.h.se=function(a){this.dispatchEvent(new gta(a,this))};
g.Sa(gta,g.Oe);g.Sa(E2,D2);E2.prototype.B=g.Ia;E2.prototype.Zt=function(){this.B();E2.Lb.Zt.call(this)};
E2.prototype.xm=function(){this.B();E2.Lb.xm.call(this)};
E2.prototype.Ep=function(){this.B();E2.Lb.Ep.call(this)};
g.Sa(F2,E2);F2.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.r(G2,g.z);G2.prototype.na=function(a,b,c,d){c=(0,g.w)(c,d||this.u);a=g.jp(a,b,c);this.o.push(a);return a};
G2.prototype.Vs=function(a,b,c,d){c=(0,g.w)(c,d||this.u);a=g.tp(a,b,c);this.o.push(a);return a};
G2.prototype.eb=function(a){g.kp(a);g.eb(this.o,a)};
G2.prototype.Y=function(){g.kp(this.o);this.o.length=0;g.z.prototype.Y.call(this)};g.r(K2,g.KL);g.h=K2.prototype;g.h.load=function(){g.KL.prototype.load.call(this);if(!L2(this)){var a=g.HB(this.player.getVideoData());if(a)a=J2(a,jta(this)),M2(this,a,!1);else{var b=this.player.getVideoData();a=b.videoId;this.B&&this.B.abort();a={method:"POST",md:(0,g.w)(this.aL,this,a),Xd:{v:a},withCredentials:!0};this.R&&(a.Xd.ptype="embedded");var c=this.player.getVideoData().Sn;c&&(a.ub={ad_tracking:c});if(b=g.GB(b))if(b=g.Bc(b),b=g.zc(b))this.B=g.yq(b,a)}}};
g.h.unload=function(){M2(this,null);this.B&&(this.B.abort(),this.B=null);g.KL.prototype.unload.call(this)};
g.h.Qc=function(a,b){if(!L2(this))return null;if("loadCustomEndscreenRenderer"==a){var c=J2(b,"new");M2(this,c);return!0}return null};
g.h.getOptions=function(){return L2(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.aL=function(a,b){var c=this.B=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=J2(c,jta(this)))}M2(this,c)};
g.h.hz=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<qua.length;f++){var k=Math.abs(b.width-qua[f]);if(-1==e||d>=k)e=f,d=k}d=rua[e];this.A&&g.yh(this.A.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],k=this.G[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Qh(e.element,Math.round(k.width*a.width),f);g.Gh(e.element,m,n);g.Kn(e.element,sua);m=k.left+k.width/2;k=k.top+l/2;g.I(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Kn(e.element,rua);g.I(e.element,d);(e=g.fe(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.yh(e,"height",f+"px")}}}}};
g.h.XG=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())Q2(this,this.u.impressionUrls),(a=g.Yr())&&this.u.visualElement&&g.ns(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.G[a];g.I(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.I(b,"ytp-ce-shown");Q2(this,c.impressionUrls);(b=g.Yr())&&g.ns(b,c.visualElement);this.player.O().A&&this.player.sa("endscreenelementshown",a)}};
g.h.YG=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.Jn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.Jn(b,"ytp-ce-shown");this.player.O().A&&this.player.sa("endscreenelementhidden",a)}};
g.h.GN=function(a){var b=this;a.target===window&&(new g.H(function(){for(var c in b.o)g.Kn(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.EA=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Hn(c,"ytp-ce-element");){g.Hn(c,"subscribe-label")&&R2(this,a);if(g.Hn(c,"ytp-ce-channel-subscribe"))return;c=g.Be(c)}if(!c||g.Hn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.eu(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.FO?(R2(this,a),this.gC(),this.player.pauseVideo(),c=g.Bc(O2(this,a.targetUrl)),c=g.zc(c),g.NN(c,void 0,a.Rb)):(c=this.player.getVideoData().pc,
c=(0,g.w)(this.xO,this,c,O2(this,a.targetUrl),a.Rb),c=(0,g.w)(this.gC,this,c),R2(this,a,c))}}};
g.h.xO=function(a,b,c){var d=g.gq(b);a&&d&&(d.v||d.list)?g.xT(this.player.app,d.v,c,d.list,!1,void 0):g.MN(b,c)};
g.h.lt=function(a,b){g.Hn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.I(a.element,"ytp-ce-element-hover"):this.player.O().o?(new g.H(function(){g.I(a.element,"ytp-ce-element-hover")},200)).start():g.I(a.element,"ytp-ce-element-hover"),Q2(this,b.aG),P2(this,b.id,!0))};
g.h.eu=function(a,b){g.Jn(a.element,"ytp-ce-element-hover");g.Jn(a.element,"ytp-ce-force-expand");P2(this,b.id,!1)};
g.h.gC=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var qua=[346,426,470,506,570,640,853,1280,1920],rua="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),sua=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var vta={nQ:"current",MR:"new"};var xta={CLOSE:"close",PR:"openUrl",UD:"subscribe"},yta={hQ:"click",CLOSE:"close",bR:"hidden",vS:"rollOut",wS:"rollOver",BS:"shown"};W2.prototype.lc=function(){var a=zta(this,function(b){return"openUrl"==b.type&&null!=b.url});
return a?a.url:null};
var nua={KP:"anchored",pD:"branding",CHANNEL:"channel",mQ:"cta",eR:"highlightText",vR:"label",PLAYLIST:"playlist",hS:"popup",GS:"speech",UD:"subscribe",QS:"title",VIDEO:"video",eT:"website"},mua={pD:"branding",YP:"card",uQ:"drawer",dR:"highlight",CR:"marker",mS:"promotion",TEXT:"text",gT:"widget"};Y2.prototype.u=function(a,b){var c=g.Ie(b.target,"label");c&&g.J(c,"iv-card-poll-choice-focused",a)};
Y2.prototype.B=function(a,b){var c=g.Ie(b.target,null,"iv-card-poll",void 0);if(c)if(a.nj)g.he("iv-card-sign-in-button",c).click();else{var d=parseInt($sa(b.target),10);if(null==a.Ce)a.choices[d].count++,a.Ce=d;else if(a.Ce!=d){var e=a.choices[a.Ce];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.Ce=d}else e=a.choices[a.Ce],e.count=Math.max(e.count-1,0),a.Ce=null;Gta(a,c);g.Cq(this.o.videoData.ae,{Xd:{action_poll_vote:1},ub:{poll_id:a.id,index:d,session_token:a.hP}});X2(this.o.logger,a.Ic.click,
void 0,5);(c=g.Yr())&&a.ce&&g.ts(c,a.ce)}};g.r(d3,g.z);g.h=d3.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.gC(a,b,{id:c});a.namespace="annotations_module";d&&this.fa.set(a,d);e&&this.ka.set(a,e);g.tL(this.context.K,[a])};
g.h.Km=function(){this.context.u.subscribe("resize",this.Cn,this)};
g.h.xa=function(){return this.Ha};
g.h.Mk=function(a,b,c,d,e,f){this.context.o.na(a,"click",g.Qa(this.Lo,b,c,d,e||[],f||0),this);this.context.o.na(a,"touchstart",g.Qa(function(){this.qv=!1}),this);
this.context.o.na(a,"touchmove",g.Qa(function(){this.qv=!0}),this)};
g.h.Lo=function(a,b,c,d,e,f){if(this.qv)return!1;f&&(f.stopPropagation(),f.preventDefault());Mta(this,a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.ye(this.xa())};
g.h.Cn=function(){};
g.h.Y=function(){this.fa.clear();this.ka.clear();g.z.prototype.Y.call(this)};g.r(h3,d3);g.h=h3.prototype;g.h.isAvailable=function(){var a;if(a=!!this.A.length)(a=this.u.getRootNode())?(a=g.Rh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Cn=function(){var a=this.isAvailable();g.Sh(this.xa(),a);g.J(this.context.K.getRootNode(),g.AM.IV_DRAWER_ENABLED,a);x2(this.u)};
g.h.destroy=function(){var a=g.lL(g.ZK(this.u));a&&a.ht(!1,void 0);try{this.u.getRootNode().removeChild(this.D)}catch(b){}g.Vo(this.W);g.kp(this.ga);this.ea&&this.ea.dispose();this.G&&this.G.dispose();d3.prototype.destroy.call(this)};
g.h.RL=function(a){this.ba.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.B.scrollTop+=a};
g.h.hC=function(a){if(!g.Hn(this.u.getRootNode(),"ytp-cards-teaser-shown")){if(this.o!=a){var b=g.Yr(),c=this.o?this.o.card.Ad:this.J;b&&c&&z2(b,[c]);this.o=a;l3(this)}if(b="none"!=this.xa().style.display)2==this.context.K.getPresentingPlayerType()?b=1==this.context.K.getAdState():(b=this.context.K.getPlayerState(),c=0==b&&0===this.context.K.getCurrentTime(),b=1==b||3==b||c);b&&a.card.teaserDurationMs&&(b={teaserText:a.card.teaserText,durationMs:a.card.teaserDurationMs},(c=g.lL(g.ZK(this.u)))&&c.ht(!0,
b));this.wa.isActive()||((!this.C||!this.ba.isActive()&&this.ca)&&Wta(this,a),this.wa.start(910+a.card.teaserDurationMs))}};
g.h.pO=function(a){this.C||(this.o=a,l3(this),Wta(this,a),f3(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1))};
g.h.uE=function(){if(this.C){X2(this.context.logger,m3(this).Ic.close);var a=g.Yr();a&&this.N&&g.ts(a,this.N);g3(this)}};
g.h.HE=function(){g.J(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.h.sG=function(){var a=g.Yr(),b=m3(this);b=b?b.Ad:this.J;a&&b&&y2(a,[b])};
g.h.rG=function(){var a=g.Yr(),b=m3(this);b=b?b.Ad:this.J;a&&b&&z2(a,[b])};
g.h.vG=function(){var a=m3(this);X2(this.context.logger,a.Ic.uC);var b=g.Yr();b&&a&&y2(b,[a.Wd,a.Ad])};
g.h.uG=function(){var a=g.Yr(),b=m3(this);a&&b&&z2(a,[b.Wd])};
g.h.tG=function(a){var b=m3(this),c=g.Yr();this.o?a?(a=this.context.logger,X2(a,b.Ic.oq),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.Wd&&g.ts(c,b.Wd)):(a=this.context.logger,X2(a,b.Ic.oq),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.Ad&&g.ts(c,b.Ad)):(a=this.context.logger,X2(a,b.Ic.oq),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.J&&g.ts(c,this.J))};g.r(n3,d3);n3.prototype.Km=function(){d3.prototype.Km.call(this);Xta(this)};
n3.prototype.show=function(){d3.prototype.show.call(this);var a=g.Yr(),b=this.annotation.data;a&&b&&(b=b.session_data)&&y2(a,[g.Qr(b.itct)])};
n3.prototype.hide=function(){d3.prototype.hide.call(this);var a=g.Yr(),b=this.annotation.data;a&&b&&(b=b.session_data)&&z2(a,[g.Qr(b.itct)])};g.r(o3,n3);g.h=o3.prototype;g.h.yO=function(a,b,c,d){this.A.stop();if(!this.B){var e=g.Rh(a);this.o||(g.Ph(a,e.width),g.Ph(b,e.width));g.yh(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.yh(c,"right","1px");this.B=!0;g.Sh(a,!0);this.C=new g.H(function(){g.I(this.xa(),"iv-branding-active")},0,this);
this.C.start()}};
g.h.ZF=function(a,b){g.Jn(this.xa(),"iv-branding-active");this.D=new g.H((0,g.w)(function(){g.Sh(a,!1);this.o||g.Ph(b,0)},this),250);
this.D.start();this.B=!1};
g.h.show=function(){if(!this.isActive){n3.prototype.show.call(this);if(!this.G){g.I(this.xa(),"iv-branding");var a=this.annotation.data;this.u=g.se("IMG",{"aria-label":"Channel watermark",src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Sh(this.u,!1);var b=g.se("DIV","branding-img-container",this.u);this.xa().appendChild(b);(b=this.annotation.lc())&&this.Mk(this.u,b,this.annotation.id,a.session_data);if(a.channel_name){var c=g.se("DIV","iv-branding-context-name");
g.De(c,a.channel_name);var d=g.se("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.o=new g.cR(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.K),this.o.da(d);b=g.se("DIV","iv-branding-context-subscribe-caret");c=g.se("DIV","branding-context-container-inner",b,c,d);g.Sh(c,!1);d=g.se("DIV","branding-context-container-outer",c);g.yh(d,"right",
a.image_width+"px");this.xa().appendChild(d);this.A=new g.H(g.Qa(this.ZF,c,d),500,this);g.A(this,this.A);this.context.o.na(this.xa(),"mouseover",(0,g.w)(this.yO,this,c,d,b,a.image_height));this.context.o.na(this.xa(),"mouseout",(0,g.w)(this.A.start,this.A,void 0))}this.G=!0}g.Sh(this.xa(),!0);this.isActive=!0;if(this.u){a=this.u;var e=void 0===e?0:e;b=g.Kh(a);c=g.Rh(a);b=(new g.vh(b.x,b.y,c.width,c.height)).width;g.Gh(a,b);e=new F2(a,[b,a.offsetTop],[b-b-e,a.offsetTop],200,ata);g.A(this,e);this.context.A.na(e,
"begin",g.Qa(g.Sh,a,!0));e.play()}}};
g.h.hide=function(){this.isActive&&(n3.prototype.hide.call(this),g.Sh(this.xa(),!1),this.isActive=!1)};
g.h.destroy=function(){this.o&&(this.o.dispose(),this.o=null);n3.prototype.destroy.call(this)};g.r(p3,n3);g.h=p3.prototype;g.h.show=function(){this.isActive||(n3.prototype.show.call(this),this.R||(Yta(this),this.R=!0),g.Sh(this.xa(),!0),g.Zf(function(){g.Jn(this.xa(),"iv-promo-inactive")},100,this),this.xa().removeAttribute("aria-hidden"),this.isActive=!0,q3(this),$ta(this),aua(this,this.G))};
g.h.hide=function(){this.isActive&&(g.I(this.xa(),"iv-promo-inactive"),this.isActive=!1,this.xa().setAttribute("aria-hidden",!0))};
g.h.Lo=function(a,b,c,d,e,f){return this.C?!1:n3.prototype.Lo.call(this,a,b,c,d,e,f)};
g.h.ys=function(a,b){b.stopPropagation();$ta(this);aua(this,a);this.o.focus()};
g.h.DF=function(a){this.J=!0;this.ys(500,a)};
g.h.CF=function(){this.J=!1;Zta(this)};
g.h.uF=function(a){a.stopPropagation();this.hide()};
g.h.vF=function(a){a.stopPropagation();q3(this);this.C=!0;g.I(this.xa(),"iv-promo-collapsed-no-delay");this.D.start()};
g.h.destroy=function(){this.D.dispose();n3.prototype.destroy.call(this)};g.r(r3,g.KL);g.h=r3.prototype;g.h.Qc=function(a,b){if(!dua(this.player.O().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.w1(b);c&&s3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(Rta(this.o,b),x2(this.player)),!0}return null};
g.h.getOptions=function(){return dua(this.player.O().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.Hp=function(){if(this.B){var a=g.eL(this.player).getVideoContentRect(!0);g.Qh(this.B.element,a.width,a.height);g.Gh(this.B.element,a.left,a.top)}if(this.o){var b=g.oL(this.player);a=this.o;b=b.width;g.J(a.D,"iv-drawer-small",426>=b);g.J(a.D,"iv-drawer-big",1280<=b)}};
g.h.mM=function(a){eua(this,a.state);g.U(a.state,2)&&(this.em()&&this.Yy()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.ht(!1))};
g.h.load=function(){g.KL.prototype.load.call(this);eua(this,g.dL(this.player));this.J++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.w)(this.cL,this,b,this.J),d=(0,g.w)(function(){this.D=null},this);
g.Ap()&&(c=iua(this,c));c={format:"XML",md:c,onError:d,Xd:{}};a.isPharma&&(c.Xd.pharma="1");c.method="POST";c.withCredentials=!0;(b=this.player.O().J.get(b))&&jua(c,b);b=b&&(b.Hn||b.Gn);if(!a.un||b)a.ae?fua(this,a.ae,c):(this.A=(0,g.w)(this.WG,this,c),this.player.addEventListener("videodatachange",this.A));g.xL(this.player,this.B.element,4);this.Hp();(b=g.IB(a))&&oua(this,b);(b=g.JB(a))&&b.featuredChannel&&pua(this,b.featuredChannel,b.annotationId||"branding",a.videoId||null,a.eventId||null)};
g.h.WG=function(a){var b=this.player.getVideoData();b.ae&&(this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null),fua(this,b.ae,a))};
g.h.unload=function(){g.CR(this.player.app,"annotations_module",void 0);g.Ab(this.G,function(a){a.destroy()});
this.H=null;this.o&&(this.o.destroy(),this.o=null,x2(this.player));this.R=!1;this.D&&(this.D.abort(),this.D=null);this.G={};this.u.hide();g.KL.prototype.unload.call(this);g.Iu(this.B);this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null)};
g.h.cL=function(a,b,c){this.D=null;!hua(this,b,a)&&(a=g.sq(c)&&c.responseXML?c.responseXML:null)&&(s3(this,a),g.I(this.player.getRootNode(),"iv-module-loaded"))};
g.h.oB=function(a){a==this.player.getVideoData().videoId&&(this.loaded?kua(this):this.load())};
g.h.em=function(){return!!this.o&&this.o.isAvailable()};
g.h.Yy=function(){this.em();return!!this.o&&this.o.C};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.em();this.o&&(a?c?f3(this.o,c,b):f3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):g3(this.o))};
g.h.ht=function(a,b){this.player.T(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.Y=function(){this.player.O().J.unsubscribe("vast_info_card_add",this.oB,this);g.Jn(this.player.getRootNode(),g.AM.IV_DRAWER_OPEN);for(var a=this.N,b=0,c=a.length;b<c;b++)g.Bp(a[b]);this.N.length=0;g.KL.prototype.Y.call(this)};g.ZL.annotations_module=r3;g.ZL.creatorendscreen=K2;})(_yt_player);
